INSERT INTO libro (nombre, descripcion, precio, stock, foto) VALUES ('libro 1', 'Descripcion 1', 100, 2, 'foto1.jpg');
INSERT INTO libro (nombre, descripcion, precio, stock, foto) VALUES ('libro 2', 'Descripcion 2', 200, 4, 'foto2.jpg');
INSERT INTO libro (nombre, descripcion, precio, stock, foto) VALUES ('libro 3', 'Descripcion 3', 300, 6, 'foto3.jpg');
INSERT INTO libro (nombre, descripcion, precio, stock, foto) VALUES ('libro 4', 'Descripcion 4', 400, 8, 'foto4.jpg');
INSERT INTO libro (nombre, descripcion, precio, stock, foto) VALUES ('libro 5', 'Descripcion 5', 500, 10, 'foto5.jpg');
INSERT INTO libro (nombre, descripcion, precio, stock, foto) VALUES ('libro 6', 'Descripcion 6', 600, 12, 'foto6.jpg');
INSERT INTO libro (nombre, descripcion, precio, stock, foto) VALUES ('libro 7', 'Descripcion 7', 700, 14, 'foto7.jpg');
INSERT INTO libro (nombre, descripcion, precio, stock, foto) VALUES ('libro 8', 'Descripcion 8', 800, 16, 'foto8.jpg');
INSERT INTO libro (nombre, descripcion, precio, stock, foto) VALUES ('libro 9', 'Descripcion 9', 900, 18, 'foto9.jpg');
INSERT INTO libro (nombre, descripcion, precio, stock, foto) VALUES ('libro 10', 'cien años de soledad 10', 1000, 20, 'foto10.jpg');